name: Deploy-to-dev

on:
  push:
    branches:
      - dev
jobs:
  Build-and-Deploy:
    runs-on: 35.236.219.144
    environment: dev
    steps:
      - name: build
        run: sudo apt install nodejs -y && node -v

