name: Deploy-to-staging

on:
  push:
    branches:
      - staging
jobs:
  Build-and-Deploy:
    runs-on: 35.236.219.144
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ls -la
