name: Deploy-to-staging

on:
  push:
    branches:
      - staging
jobs:
  Build-and-Deploy:
    runs-on: 35.236.219.144
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: SSH server 
        run: echo "${{ secrets.SSH_KEY }}" > ./key && chmod 600 ./key && ssh -i key aman@35.236.219.144 "rm -rf /var/www/html/node-staging/*"
      - name: Copy build to server
        run: scp -i ./key -r ./* aman@35.236.219.144:/var/www/html/node-staging/
