name: Deploy-to-test

on:
  push:
    branches:
      - test
jobs:
  Build-and-Deploy:
    runs-on: 35.236.219.144
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ls -la
